UserOptionsFilePath: "%LocalAppData%\\SMZ3CasRandomizer\\msu-user-settings.yml"
MsuCachePath: "%LocalAppData%\\SMZ3CasRandomizer"
SaveDataDirectory: "%LocalAppData%\\SMZ3CasRandomizer"
ContinuousReshuffleSeconds: 60
MsuWindowDisplayRandomButton: false
MsuWindowDisplayShuffleButton: false
MsuWindowDisplayContinuousButton: false
MsuWindowDisplayOptionsButton: false
MsuWindowDisplaySelectButton: true
DisableHardwareMode: true
ForcedMsuType: "SMZ3 Combo Randomizer"
MsuWindowTitle: SMZ3 Cas' Randomizer
MsuTypeNameOverrides:
  "Super Metroid / A Link to the Past Combination Randomizer Legacy": "SMZ3 Classic (Metroid First)"
  "Super Metroid / A Link to the Past Combination Randomizer": "SMZ3 Combo Randomizer"
  "The Legend of Zelda": "Zelda 1 SNES Port"
  "Metroid": "Metroid 1 SNES Port"
Smz3MsuTypes:
  - SMZ3 Classic (Metroid First)
  - SMZ3 Combo Randomizer
DisableMessenger: true
MsuTypeFilter:
  - SMZ3 Combo Randomizer
  - SMZ3 Classic (Metroid First)
  - Super Metroid
  - "The Legend of Zelda: A Link to the Past"
